name: 'finlend'
version: '1.0.0'
config-version: 2
profile: 'finlend'

models:
  finlend:
    staging:
      +materialized: view
    marts:
      +materialized: table

vars:
  incremental_lookback_days: 3

seeds:
  finlend:
    +schema: reference